site:
  baseline: Architecture
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: Bunla oynama
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Merve Sancar
theme: hyde
